### PR TITLE
Changed file type + fixed typos

### PR DESCRIPTION
**Pull request by 2br-2b**

### CODE REVIEW

**Comment by 2br-2b** [comment]
Thank you so much for open-sourcing Sandboxie! I never would have used it otherwise, but now I use it all of the time! I look forward to seeing how the open-source community improves this already-great product!

**Comment by CaliSunUSA** [comment]
People that are not tech savvy are the ones that need help from this product the most, but the developers are excluding everyone and only inviting techies by not creating installation file. (exe or msi)

Shame on you by excluding everyone but techies from being protected on the internet.

**Comment by jojoharry16** [comment]
My God this makes it easier to read, thanks

**Review by SandboxieDev — APPROVED** [review]
Looks good thanks!

**Comment by LPeisen** [comment]
邮件已经收到，尽快给您回复。

**Pull request merged**
